services:
  mqtt2prometheus:
    build: https://github.com/hikhvar/mqtt2prometheus.git
    image: my-mqtt2prometheus
    container_name: mqtt2prometheus
    restart: always
    volumes:
      - ./mqtt2prometheus.yaml:/config.yaml

    # inutile d'exporter ce port 
    #    ports:
    #      - 9941:9641

    networks:
      - teleinfo

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.size=1GB'
    restart: always
#    ports:
#      - 3001:9090
    volumes:
      - ./prometheus-conf:/etc/prometheus
      - ./prometheus-data:/prometheus
    networks:
      - teleinfo

  mosquitto:
    image: eclipse-mosquitto:2.0-openssl
    restart: always
    ports:
      # port 8883 configure en tls-psk
      - 8883:8883
      # port 1883 configuré en anonymous sans tls - ne pas mapper à l'extérieur
      # port 1883 réservé à l'accès en local par mqtt2prometheus

    volumes:
      - ./mosquitto-conf:/mosquitto/config
    networks:
      - teleinfo

  grafana:
    image:  grafana/grafana-enterprise
    container_name: grafana
    restart: always
      #    ports:
      # - 3002:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-logs:/var/log/grafana
        #      - ./grafana-conf:/etc/grafana
    networks:
      - traefik
      - teleinfo

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-lan"
      - "traefik.http.routers.to-teleinfo.rule=Host(`teleinfo.vintz.fr`)"
      - "traefik.http.routers.to-teleinfo.tls.certresolver=vintz-wildcard"
      - "traefik.http.routers.to-teleinfo.tls.domains[0].main=*.vintz.fr"
      - "traefik.http.services.teleinfo.loadbalancer.server.port=3000"

networks:
  teleinfo:

  traefik:
    name: "traefik-lan"
    external: true

